name: Deploy Workers Preview

on:
  pull_request:
    paths:
      - './*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Workers Preview
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: 'dev'
